services:
  - type: web
    name: cv-screening-api
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --only-binary=all -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ENVIRONMENT
        value: production
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health

