services:
  - type: web
    name: cv-screening-api
    env: python
    plan: starter
    buildCommand: |
  python3.9 -m pip install --upgrade pip==23.0.1
  python3.9 -m pip install --no-cache-dir --only-binary=all -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ENVIRONMENT
        value: production
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health

