services:
  - type: web
    name: cv-screening-api
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-use-pep517 -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health


