services:
  - type: web
    name: cretzo-ai
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health

